Repository rootstrap/blog, pull requests merged in 2020-07, with the labels that each got.

#126 Animations in react native
  content/Animations in React Native - Fernanda Toledo.md
  content/images/animation.jpeg
Labels: style review

#92 Statistics datascience 2
  content/Understanding Basic Statistics for Machine Learning Models - Part 2 - Mikaela Pisani.md
  content/images/bayesian-2889576_1280.png
  content/images/business-361126_1280.jpg
Labels: style review

#129 Bias variance
  content/Bias_variance - Mikaela pisani.md
  content/images/bias_variance_tradeoff.png
  content/images/formula_MSE.png
  content/images/plot_bias_variance_trainingsize.png
  content/images/plot_iterations_error.png
  content/images/plot_iterations_overfitting.png
  content/images/plot_trainingsize_error.png
Labels: content review

#90 add article - skills for data scientist
  content/Skills for Data Scientist - Mikaela Pisani.md
  content/images/Skills-Data-Scientist-v1.png
Labels: style review

#89 Data science
  content/images/Data_science.png
  content/images/RS-blog-What-Is-Data-Science-v1.png
  content/images/data_pipeline.png
  content/images/privacy_ethics.png
  content/what is data science - Mikaela Pisani.md
Labels: style review

#106 Rails N + 2 queries
  content/Rails N + 2 queries - Bruno Vezoli.md
  content/images/forest_bridge.jpg
Labels: low hanging fruit

#139 Voice over
  content/Voice Over - Fernanda Toledo.md
  content/images/blindfold.jpg
  content/images/glasses.jpg
Labels: style review

#143 HTTPS is not enough
  content/HTTPS is not enough - Pablo Blanco.md
  content/images/https-not-enough-mitm.png
  content/images/https-not-enough.jpg
Labels: content review, style review

#124 How to customize the display name of dynamic ActiveAdmin search filters
  content/How to customize the display name of ActiveAdmin search filters- Juan Ferrari.md
Labels: ready

#146 Prediction experiment article
  content/A prediction experiment with Machine Learning - Bruno Michetti.md
  content/images/comparison-exponential-original-simulated.png
  content/images/comparison-normal-original-simulated.png
  content/images/no-distribution-example.png
  content/images/one-hot-econding-example.png
  content/images/prediction-error-definitions.png
  content/images/regression-concept.png
Labels: ready

#142 Exception Tracking
  content/Exception Tracking - Tiziana Romani.md
Labels: low hanging fruit, style review

#123 add blog for Simulation Methods
  content/Simulation_Methods_Mikaela_Pisani.md
Labels: content review
