Repository rootstrap/blog, pull requests merged in 2020-01, with the labels that each got.

#64 Why you should use Gatsby to build your landing page
  content/Why you should use GatsbyJS to build your landing page - Nicolás Santos.md
  content/images/gatsby.png
Labels: style review

#57 4 common vulnerabilities of web apps
  content/4 common vulnerabilities of web apps - Alvaro Acuña.md
Labels: ready

#70 RS Week Mateo Fernández
  content/What I've Learned From Rootstrap Week.md
  content/images/rsweek1.jpeg
  content/images/rsweek2.jpeg
Labels: ready, style review
