Repository rootstrap/blog, pull requests merged in 2020-05, with the labels that each got.

#88 Engineering Hiring Process @ RS
  content/Engineering Hiring Process.md
  content/images/finding-candidates.jpg
  content/images/hiring-steps.jpg
Labels: ready

#98 Introducing yaaf
  content/Hello yaaf - Juan Manuel Ramallo.md
Labels: ready

#102 Best Buy Ruby post
  content/Access the world's most powerful retail APIs with Best Buy Ruby - Sandro Damilano.md
  content/images/internet_sign.jpg
Labels: content review

#100 Introduction to Android Arch. Components.
  content/Android Arc Components - Amaury Ricard.md
  content/images/arch_components.png
  content/images/lifecycle.jpg
Labels: style review
