Repository rootstrap/blog, pull requests merged in 2020-06, with the labels that each got.

#87 Gems you want to have in your Rails API
  content/Gems You Want To Have In Your Rails API - Juan Diego Rosales.md
Labels: ready

#110 Online payments made SIMPLE - How to work with Stripe
  content/How to work with Stripe.md
  content/images/payment.jpg
Labels: style review

#104 Active Admin 2FA with OneLogin
  content/ActiveAdmin 2FA with OneLogin.md
  content/images/2fa.jpg
Labels: style review

#111 Some iOS good practices article
  content/iOS/Practices/iOS-practices.md
Labels: content review, style review

#108 React Query and management of server state
  content/React Query and management of server state - Nicolás Santos.md
Labels: content review
