Repository rootstrap/blog, pull requests merged in 2021-07, with the labels that each got.

#216 Pyenv and Pipenv article. First version
  content/A good way to manage your Python projects using Pyenv and Pipenv.md
  content/images/pipenv_shell.png
  content/images/python_environments.png
Labels: style review

#212 Test intro
  content/Testing in Django - Basics - useful tools and good practices.md
Labels: style review

#179 Article/consumer privacy regulations ccpa and gdpr
  content/Consumer Privacy Regulations CCPA and GDPR - Pablo Blanco.md
  content/images/internet-privacy.jpg
Labels: content review, style review

#182 Why is documentation important for development
  content/Documentation Guidelines - Sebastián Caraballo.md
  content/images/notion-template-05.png
  content/images/postman.jpg
  content/images/why_documenting_matters.jpg
Labels: style review

#208 How to integrate a Typography System in React Native the right way
  content/How to integrate a Typography System in React Native the right way - Agustina Chaer.md
  content/images/rn_typography_main.jpg
Labels: style review

#170 Simple dynamic settings for Django
  content/Simple dynamic settings for Django - Jorge Michelena.md
Labels: style review

#204 Blog/how to make your first gem
  content/How to Make My First Gem - Timothy Peraza.md
  content/images/bin_folder.png
  content/images/lib_folder.png
  content/images/rsgem_structure.png
  content/images/spec_folder.png
Labels: style review

#198 Add useStyles article
  content/images/useStylesBanner.jpg
  content/images/useStylesMeme.jpg
  content/useStyles: a hook to manage your styles - Agustín Prieto - EN.md
  content/useStyles: a hook to manage your styles - Agustín Prieto - ES.md
Labels: style review

#206 android cicd article
  content/Android App Build and Release Automation - Sebastian Lopez.md
  content/images/android_robot.jpg
Labels: content review, style review

#95 Data cleaning
  content/Data cleaning - Mikaela Pisani.md
  content/images/one_hot.jpg
Labels: style review

#96 Machine learning intro
  content/IntroductionMachineLearning - Mikaela Pisani.md
  content/images/AI_ML_DL.png
Labels: style review

#134 Solution for common problems
  content/Solution for common problems - Section 1 - Data - Mikaela Pisani.md
  content/images/big_data.png
Labels: content review

#131 added blog post data visualization
  content/Data Visualization - Mikaela Pisani.md
  content/images/boxplot.png
Labels: content review

#127 add ensembles blog
  content/Ensembles_MikaelaPisani.md
  content/images/Ensembles.png
Labels: content review
